# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

env:
    PACKAGE_PREFIX: 1
    OCTOPUS_PACKAGE_NAME: EnthisuasticPromotions
    OCTOPUS_SPACE_NAME: "Octopus Server"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install Pester
        id: install-pester
        run: Install-Module "Pester" -Force
        shell: pwsh
       
      - name: Run Pester Tests
        id: pester-tests
        run: |
          Import-Module -Name "Pester"
          $configuration = [PesterConfiguration]::Default
          $configuration.Run.Exit = $true
          Invoke-Pester -configuration $configuration
        shell: pwsh