# Action for pushes to main branch
# It installs pester, runs the pester tests
# packages the script up and sends it to deploy.octopus.app

name: CI

on:
  push:
    branches: [ main ]

env:
    PACKAGE_PREFIX: 1
    OCTOPUS_PACKAGE_NAME: EnthisuasticPromotions
    OCTOPUS_SPACE_NAME: "Octopus Server"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Pester
        id: install-pester
        run: Install-Module "Pester" -Force
        shell: pwsh
       
      - name: Run Pester Tests
        id: pester-tests
        run: |
          Import-Module -Name "Pester"
          $configuration = [PesterConfiguration]::Default
          $configuration.Run.Exit = $true
          Invoke-Pester -configuration $configuration
        shell: pwsh

      - name: Set version
        id: set-version
        run: echo "PACKAGE_VERSION=$PACKAGE_PREFIX.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    
      - name: Make package directories
        run: mkdir -p ./packagesoutput/$OCTOPUS_PACKAGE_NAME    
      
      - name: Move PS script to build folder
        id: move-ps-script-to-build-folder
        run: cp ./enthusiastic-promoter.ps1 ./packagesoutput/$OCTOPUS_PACKAGE_NAME
    
      - name: Install Octopus CLI
        run: |
          sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
          curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
          sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
          sudo apt update && sudo apt install octopuscli 
          
      - name: Package
        run: octo pack --id="$OCTOPUS_PACKAGE_NAME" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./packagesoutput/$OCTOPUS_PACKAGE_NAME" --outFolder="./packages"
          
      - name: Push to Octopus
        run: octo push --package="./packages/$OCTOPUS_PACKAGE_NAME.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}" --space="$OCTOPUS_SPACE_NAME"
