# Action that is used for PRs to main branch
# It installs pester and runs the pester tests only

name: CI

on:
  pull_request:
    branches: [ main ]

env:
  OCTOPUS_PACKAGE_NAME: EnthisuasticPromotions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Pester
        id: install-pester
        run: Install-Module "Pester" -Force
        shell: pwsh
       
      - name: Run Pester Tests
        id: pester-tests
        run: |
          Import-Module -Name "Pester"
          $configuration = [PesterConfiguration]::Default
          $configuration.Run.Exit = $true
          Invoke-Pester -configuration $configuration
        shell: pwsh

      - name: Install Octo CLI
        uses: OctopusDeploy/install-octopus-cli-action@main
        with:
          version: latest

      - name: make file
        id: make-file
        run: New-Item "$OCTOPUS_PACKAGE_NAME.1.0.0.txt"
        shell: pwsh

      - name: Push to Octopus Deploy
        uses: OctopusDeploy/push-package-action@main
        with:
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          server: ${{ secrets.OCTOPUS_SERVER }}
          space: "Octopus Server"
          packages: "$OCTOPUS_PACKAGE_NAME.1.0.0.txt"